export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_NONE = 'None' as const;
export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_WATER_STANDPIPE = 'Water Standpipe' as const;
export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_STANDPIPE_PIEZOMETER = 'Standpipe Piezometer' as const;
export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_INCLINOMETER = 'Inclinometer' as const;
export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_CUSTOM = 'Custom' as const;

export const END_OF_BOREHOLE_OTHER_INSTALLATIONS_LIST = [
    END_OF_BOREHOLE_OTHER_INSTALLATIONS_NONE,
    END_OF_BOREHOLE_OTHER_INSTALLATIONS_WATER_STANDPIPE,
    END_OF_BOREHOLE_OTHER_INSTALLATIONS_STANDPIPE_PIEZOMETER,
    END_OF_BOREHOLE_OTHER_INSTALLATIONS_INCLINOMETER,
    END_OF_BOREHOLE_OTHER_INSTALLATIONS_CUSTOM,
] as const;
