import { BaseBlock } from "@/interfaces/Block";
import { SptBlock } from "@/interfaces/SptBlock";

export function serializeSptBlock(block: BaseBlock & SptBlock): string {
    return JSON.stringify({
        id: block.id,
        blockId: block.blockId,
        boreholeId: block.boreholeId,
        blockTypeId: block.blockTypeId,
        sptIndex: block.sptIndex,
        disturbedSampleIndex: block.disturbedSampleIndex,
        dayWorkStatus: block.dayWorkStatus,
        topDepthInMetres: block.topDepthInMetres,
        baseDepthInMetres: block.baseDepthInMetres,
        description: block.description,
        seatingIncBlows1: block.seatingIncBlows1,
        seatingIncPen1: block.seatingIncPen1,
        seatingIncBlows2: block.seatingIncBlows2,
        seatingIncPen2: block.seatingIncPen2,
        mainIncBlows1: block.mainIncBlows1,
        mainIncPen1: block.mainIncPen1,
        mainIncBlows2: block.mainIncBlows2,
        mainIncPen2: block.mainIncPen2,
        mainIncBlows3: block.mainIncBlows3,
        mainIncPen3: block.mainIncPen3,
        mainIncBlows4: block.mainIncBlows4,
        mainIncPen4: block.mainIncPen4,
        sptNValue: block.sptNValue,
        totalMainPenetrationInMillimetres: block.totalMainPenetrationInMillimetres,
        recoveryInPercentage: block.recoveryInPercentage,
        recoveryLengthInMillimetres: block.recoveryLengthInMillimetres,
        colourProperties: block.colourProperties,
        soilProperties: block.soilProperties,
        isSeatingIncBlows1Active: block.isSeatingIncBlows1Active,
        isSeatingIncBlows2Active: block.isSeatingIncBlows2Active,
        isMainIncBlows1Active: block.isMainIncBlows1Active,
        isMainIncBlows2Active: block.isMainIncBlows2Active,
        isMainIncBlows3Active: block.isMainIncBlows3Active,
        isMainIncBlows4Active: block.isMainIncBlows4Active,
        isSeatingIncPen1Active: block.isSeatingIncPen1Active,
        isSeatingIncPen2Active: block.isSeatingIncPen2Active,
        isMainIncPen1Active: block.isMainIncPen1Active,
        isMainIncPen2Active: block.isMainIncPen2Active,
        isMainIncPen3Active: block.isMainIncPen3Active,
        isMainIncPen4Active: block.isMainIncPen4Active,
    });
}